def questions():
    # Based on the PCL-5 instrument

    prompt = "In the past month, how much were you bothered by:"

    info = [
        {"id": 1,
         "text": "Repeated, disturbing, and unwanted memories of a stressful experience?",
         "relevant_mood": "stressed"},
        {"id": 2,
         "text": "Repeated, disturbing dreams of the stressful experience?",
         "relevant_mood": "stressed"},
        {"id": 3,
         "text": "Suddenly feeling or acting as if the stressful experience were actually happening again (as if you were actually back there reliving it)?",
         "relevant_mood": "stressed"},
        {"id": 4,
         "text": "Feeling very upset when something reminded you of the stressful experience?",
         "relevant_mood": "stressed"},
        {"id": 5,
         "text": "Having strong physical reactions when something reminded you of the stressful experience (for example, heart pounding, trouble breathing, sweating)?",
         "relevant_mood": "stressed"},
        {"id": 6,
         "text": "Avoiding memories, thoughts, or feelings related to the experience?",
         "relevant_mood": "happy"},
        {"id": 7,
         "text": "Avoiding external reminders of the stressful experience (for example, people, places, conversations, activities, objects, or situations)?",
         "relevant_mood": "happy"},
        {"id": 8,
         "text": "Trouble remembering important parts of the stressful experience?",
         "relevant_mood": "motivation"},
        {"id": 9,
         "text": "Having strong negative beliefs about yourself, other people, or the world (for example, having thoughts such as: I am bad, there is something seriously wrong with me, no one can be trusted, the world is completely dangerous)?",
         "relevant_mood": "happy"},
        {"id": 10,
         "text": "Blaming yourself or someone else for the stressful experience or what happened after it?",
         "relevant_mood": "happy"},
        {"id": 11,
         "text": "Having strong negative feelings such as fear, horror, anger, guilt, or shame?",
         "relevant_mood": "happy"},
        {"id": 12,
         "text": "Loss of interest in activities that you used to enjoy?",
         "relevant_mood": "motivation"},
        {"id": 13,
         "text": "Feeling distant or cut off from other people?",
         "relevant_mood": "motivation"},
        {"id": 14,
         "text": "Trouble experiencing positive feelings (for example, being unable to feel happiness or have loving feelings for people close to you)?",
         "relevant_mood": "happy"},
        {"id": 15,
         "text": "Irritable behavior, angry outbursts, or acting aggressively?",
         "relevant_mood": "happy"},
        {"id": 16,
         "text": "Taking too many risks or doing things that could cause you harm?",
         "relevant_mood": "motivation"},
        {"id": 17,
         "text": "Being “superalert” or watchful or on guard?",
         "relevant_mood": "stressed"},
        {"id": 18,
         "text": "Feeling jumpy or easily startled?",
         "relevant_mood": "stressed"},
        {"id": 19,
         "text": "Having difficulty concentrating?",
         "relevant_mood": "stressed"},
        {"id": 20,
         "text": "Trouble falling or staying asleep?",
         "relevant_mood": "stressed"}
    ]

    scale = "0: Not At All, 1: A Little Bit, 2: Moderately, 3: Quite A Bit, 4: Extremely"

    return info, scale, prompt